//! `post contract`: the output contract compiled into this binary.
//!
//! The samples are `contract/samples/`, produced by `tests/contract_samples.rs`
//! from the real commands and embedded here at build time. Consumers test
//! against `post contract samples --dir <tmp>` from the binary they will run,
//! so a consumer suite can never pass against a vendored copy that has drifted
//! from the installed producer.

use crate::cli::{ContractArgs, ContractCommand};
use crate::command_result::CommandResult;
use crate::error::{AppError, AppResult};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

/// One served skill file as it was when this binary was built.
#[derive(Debug, Serialize)]
pub(crate) struct SkillFile {
    pub path: &'static str,
    pub sha256: &'static str,
    /// Carries a skill-render fence marker, so a rendered copy may differ.
    pub fenced: bool,
}

// SKILL_ROOT, SKILL_COVERED, and SKILL_MANIFEST, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/skill_manifest.rs"));

macro_rules! sample {
    ($name:literal) => {
        (
            $name,
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/contract/samples/",
                $name
            )),
        )
    };
}

/// Every checked-in sample. `tests/contract_samples.rs` fails when this list
/// and `contract/samples/` disagree in either direction.
pub(crate) const SAMPLES: &[(&str, &str)] = &[
    sample!("bridge-deliver-delivered.json"),
    sample!("bridge-deliver-rejected.json"),
    sample!("bridge-deliver-retry.json"),
    sample!("channels.json"),
    sample!("chat-emote.json"),
    sample!("chat.json"),
    sample!("doctor.json"),
    sample!("inbox.json"),
    sample!("participant-bind.json"),
    sample!("participant-show.json"),
    sample!("profile-avatar.json"),
    sample!("profile-list.json"),
    sample!("profile-show.json"),
    sample!("rooms.json"),
    sample!("version.json"),
    sample!("watch-snapshot-cursor-unusable.jsonl"),
    sample!("watch-snapshot-digest.jsonl"),
    sample!("watch-snapshot.jsonl"),
    sample!("who.json"),
];

#[derive(Serialize)]
struct SamplesOutput {
    ok: bool,
    samples: BTreeMap<&'static str, &'static str>,
}

#[derive(Serialize)]
struct SamplesWrittenOutput {
    ok: bool,
    dir: String,
    samples: Vec<&'static str>,
}

#[derive(Serialize)]
struct SkillManifestOutput {
    ok: bool,
    root: &'static str,
    covered: &'static [&'static str],
    count: usize,
    files: &'static [SkillFile],
}

#[derive(Serialize)]
pub(super) struct SkillVerifyOutput {
    ok: bool,
    pub(super) verdict: &'static str,
    served: String,
    kind: &'static str,
    resolved: String,
    checked: usize,
    pub(super) mismatched: Vec<&'static str>,
    pub(super) missing: Vec<&'static str>,
    pub(super) extra: Vec<String>,
    rendered_unverified: Vec<&'static str>,
}

pub(super) fn run(args: &ContractArgs, pretty: bool) -> AppResult<CommandResult> {
    match &args.command {
        ContractCommand::SkillManifest { verify: None } => CommandResult::json(
            &SkillManifestOutput {
                ok: true,
                root: SKILL_ROOT,
                covered: SKILL_COVERED,
                count: SKILL_MANIFEST.len(),
                files: SKILL_MANIFEST,
            },
            pretty,
        ),
        ContractCommand::SkillManifest {
            verify: Some(served),
        } => {
            let output = verify_served(served)?;
            // Exit 1 for anything short of a match: drift or unverified.
            let not_a_match = !output.ok;
            let mut result = CommandResult::json(&output, pretty)?;
            if not_a_match {
                result.exit_code = 1;
            }
            Ok(result)
        }
        ContractCommand::Samples { dir: None } => CommandResult::json(
            &SamplesOutput {
                ok: true,
                samples: SAMPLES.iter().copied().collect(),
            },
            pretty,
        ),
        ContractCommand::Samples { dir: Some(dir) } => {
            write_samples(dir)?;
            CommandResult::json(
                &SamplesWrittenOutput {
                    ok: true,
                    dir: dir.display().to_string(),
                    samples: SAMPLES.iter().map(|(name, _)| *name).collect(),
                },
                pretty,
            )
        }
    }
}

/// Write each sample as `<dir>/<name>`, replacing a same-named file whole: a
/// temporary sibling is written, then renamed over the target.
fn write_samples(dir: &Path) -> AppResult<()> {
    std::fs::create_dir_all(dir)
        .map_err(|error| AppError::io("create contract samples directory", dir, error))?;
    for (name, body) in SAMPLES {
        let target = dir.join(name);
        let temporary = dir.join(format!(".{name}.{}.tmp", std::process::id()));
        std::fs::write(&temporary, body)
            .map_err(|error| AppError::io("write contract sample", &temporary, error))?;
        std::fs::rename(&temporary, &target).map_err(|error| {
            let _ = std::fs::remove_file(&temporary);
            AppError::io("publish contract sample", &target, error)
        })?;
    }
    Ok(())
}

/// Check a served skill directory against the manifest built into this
/// binary. The served root's kind is recorded: a symlink (the estate's
/// default: every served `post` path links into a checkout) is checked through
/// the files it resolves to; a real directory is a rendered copy and is checked
/// as served. In a rendered copy, a file whose source carries fence markers
/// may legitimately differ, so it is listed as rendered_unverified and the
/// verdict is `unverified`: not drift, and not a match either, because this
/// binary cannot strip fences to prove the rendering faithful. Everything else
/// must match byte for byte, with nothing missing and nothing extra in the
/// covered subtrees.
pub(super) fn verify_served(served: &Path) -> AppResult<SkillVerifyOutput> {
    verify_against(served, SKILL_MANIFEST)
}

fn verify_against(served: &Path, manifest: &[SkillFile]) -> AppResult<SkillVerifyOutput> {
    let link = std::fs::symlink_metadata(served)
        .map_err(|error| AppError::io("inspect served skill path", served, error))?;
    let kind = if link.file_type().is_symlink() {
        "symlink"
    } else if link.is_dir() {
        "copy"
    } else {
        return Err(AppError::invalid_argument(format!(
            "served skill path {} is neither a directory nor a symlink to one",
            served.display()
        )));
    };
    let resolved = std::fs::canonicalize(served)
        .map_err(|error| AppError::io("resolve served skill path", served, error))?;
    if !resolved.is_dir() {
        return Err(AppError::invalid_argument(format!(
            "served skill path {} does not resolve to a directory",
            served.display()
        )));
    }
    let mut found = BTreeMap::new();
    for covered in SKILL_COVERED {
        collect_served(served, &served.join(covered), &mut found)?;
    }
    let mut mismatched = Vec::new();
    let mut missing = Vec::new();
    let mut rendered_unverified = Vec::new();
    let mut expected = BTreeSet::new();
    for file in manifest {
        expected.insert(file.path);
        let Some(path) = found.get(file.path) else {
            missing.push(file.path);
            continue;
        };
        let bytes = std::fs::read(path)
            .map_err(|error| AppError::io("read served skill file", path, error))?;
        let digest: String = Sha256::digest(&bytes)
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect();
        if digest == file.sha256 {
            continue;
        }
        if kind == "copy" && file.fenced {
            rendered_unverified.push(file.path);
        } else {
            mismatched.push(file.path);
        }
    }
    let extra: Vec<String> = found
        .keys()
        .filter(|path| !expected.contains(path.as_str()))
        .cloned()
        .collect();
    let verdict = if !(mismatched.is_empty() && missing.is_empty() && extra.is_empty()) {
        "drift"
    } else if !rendered_unverified.is_empty() {
        "unverified"
    } else {
        "match"
    };
    Ok(SkillVerifyOutput {
        ok: verdict == "match",
        verdict,
        served: served.display().to_string(),
        kind,
        resolved: resolved.display().to_string(),
        checked: manifest.len(),
        mismatched,
        missing,
        extra,
        rendered_unverified,
    })
}

/// The served files in one covered subtree, keyed by `/`-joined relative
/// path. Symlinks are followed; dot-files are skipped, as at build time.
fn collect_served(
    root: &Path,
    path: &Path,
    found: &mut BTreeMap<String, PathBuf>,
) -> AppResult<()> {
    let Ok(metadata) = std::fs::metadata(path) else {
        return Ok(());
    };
    if metadata.is_dir() {
        let entries = std::fs::read_dir(path)
            .map_err(|error| AppError::io("read served skill directory", path, error))?;
        for entry in entries {
            let entry =
                entry.map_err(|error| AppError::io("read served skill directory", path, error))?;
            if !entry.file_name().to_string_lossy().starts_with('.') {
                collect_served(root, &entry.path(), found)?;
            }
        }
    } else if metadata.is_file() {
        let relative = path
            .strip_prefix(root)
            .map_err(|_| AppError::invalid_argument("served file outside its root"))?
            .components()
            .map(|part| part.as_os_str().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
            .join("/");
        found.insert(relative, path.to_path_buf());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn digest(text: &str) -> &'static str {
        let hex: String = Sha256::digest(text.as_bytes())
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect();
        Box::leak(hex.into_boxed_str())
    }

    /// A rendered copy of a fenced file differs from its source by design:
    /// never drift, but never a match either, since nothing here proves the
    /// rendering faithful. The same difference in an unfenced file, or
    /// anywhere behind a symlink, is drift.
    #[test]
    fn a_rendered_copy_of_a_fenced_file_is_unverified_not_drift() {
        let source = "shared\n<!-- mac-only -->\nmac\n<!-- /mac-only -->\n";
        let manifest = [
            SkillFile {
                path: "SKILL.md",
                sha256: digest(source),
                fenced: true,
            },
            SkillFile {
                path: "references/plain.md",
                sha256: digest("plain\n"),
                fenced: false,
            },
        ];
        let root = crate::test_support::test_root("skill-rendered-copy");
        let copy = root.join("copy");
        std::fs::create_dir_all(copy.join("references")).expect("copy dirs");
        std::fs::write(copy.join("SKILL.md"), "shared\n").expect("rendered file");
        std::fs::write(copy.join("references/plain.md"), "plain\n").expect("plain file");
        let report = verify_against(&copy, &manifest).expect("verify copy");
        assert_eq!(report.kind, "copy");
        assert_eq!(report.verdict, "unverified");
        assert!(!report.ok, "an unverified copy is not a match");
        assert_eq!(report.rendered_unverified, vec!["SKILL.md"]);

        // A copy whose fenced file is byte-identical to its source is a match.
        std::fs::write(copy.join("SKILL.md"), source).expect("unrendered file");
        let report = verify_against(&copy, &manifest).expect("verify identical copy");
        assert_eq!(report.verdict, "match");
        assert!(report.ok);
        assert!(report.rendered_unverified.is_empty());
        std::fs::write(copy.join("SKILL.md"), "shared\n").expect("re-render file");

        std::fs::write(copy.join("references/plain.md"), "edited\n").expect("edit plain");
        let report = verify_against(&copy, &manifest).expect("verify edited copy");
        assert_eq!(report.verdict, "drift");
        assert_eq!(report.mismatched, vec!["references/plain.md"]);

        // Behind a symlink the served bytes are the source: no rendering
        // excuse applies.
        std::fs::write(copy.join("references/plain.md"), "plain\n").expect("restore plain");
        let link = root.join("link");
        std::os::unix::fs::symlink(&copy, &link).expect("served symlink");
        let report = verify_against(&link, &manifest).expect("verify symlink");
        assert_eq!(report.kind, "symlink");
        assert_eq!(report.verdict, "drift");
        assert_eq!(report.mismatched, vec!["SKILL.md"]);
        crate::test_support::trash_test_root(&root);
    }
}
